/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedAlunosAlunoIdRouteImport } from './routes/_authenticated/alunos.$alunoId'
import { Route as AuthenticatedDemandasCasamentoRouteImport } from './routes/_authenticated/demandas.casamento'
import { Route as AuthenticatedDemandasEnsaioRouteImport } from './routes/_authenticated/demandas.ensaio'
import { Route as AuthenticatedDemandasFestaAniversarioRouteImport } from './routes/_authenticated/demandas.festa-aniversario'
import { Route as AuthenticatedTurmasIndexRouteImport } from './routes/_authenticated/turmas.index'
import { Route as AuthenticatedTurmasTurmaIdRouteImport } from './routes/_authenticated/turmas.$turmaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlunosAlunoIdRoute =
  AuthenticatedAlunosAlunoIdRouteImport.update({
    id: '/alunos/$alunoId',
    path: '/alunos/$alunoId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemandasCasamentoRoute =
  AuthenticatedDemandasCasamentoRouteImport.update({
    id: '/demandas/casamento',
    path: '/demandas/casamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemandasEnsaioRoute =
  AuthenticatedDemandasEnsaioRouteImport.update({
    id: '/demandas/ensaio',
    path: '/demandas/ensaio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemandasFestaAniversarioRoute =
  AuthenticatedDemandasFestaAniversarioRouteImport.update({
    id: '/demandas/festa-aniversario',
    path: '/demandas/festa-aniversario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTurmasIndexRoute =
  AuthenticatedTurmasIndexRouteImport.update({
    id: '/turmas/',
    path: '/turmas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTurmasTurmaIdRoute =
  AuthenticatedTurmasTurmaIdRouteImport.update({
    id: '/turmas/$turmaId',
    path: '/turmas/$turmaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/alunos/$alunoId': typeof AuthenticatedAlunosAlunoIdRoute
  '/demandas/casamento': typeof AuthenticatedDemandasCasamentoRoute
  '/demandas/ensaio': typeof AuthenticatedDemandasEnsaioRoute
  '/demandas/festa-aniversario': typeof AuthenticatedDemandasFestaAniversarioRoute
  '/turmas/$turmaId': typeof AuthenticatedTurmasTurmaIdRoute
  '/turmas/': typeof AuthenticatedTurmasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/alunos/$alunoId': typeof AuthenticatedAlunosAlunoIdRoute
  '/demandas/casamento': typeof AuthenticatedDemandasCasamentoRoute
  '/demandas/ensaio': typeof AuthenticatedDemandasEnsaioRoute
  '/demandas/festa-aniversario': typeof AuthenticatedDemandasFestaAniversarioRoute
  '/turmas/$turmaId': typeof AuthenticatedTurmasTurmaIdRoute
  '/turmas': typeof AuthenticatedTurmasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/alunos/$alunoId': typeof AuthenticatedAlunosAlunoIdRoute
  '/_authenticated/demandas/casamento': typeof AuthenticatedDemandasCasamentoRoute
  '/_authenticated/demandas/ensaio': typeof AuthenticatedDemandasEnsaioRoute
  '/_authenticated/demandas/festa-aniversario': typeof AuthenticatedDemandasFestaAniversarioRoute
  '/_authenticated/turmas/$turmaId': typeof AuthenticatedTurmasTurmaIdRoute
  '/_authenticated/turmas/': typeof AuthenticatedTurmasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/financeiro'
    | '/painel'
    | '/alunos/$alunoId'
    | '/demandas/casamento'
    | '/demandas/ensaio'
    | '/demandas/festa-aniversario'
    | '/turmas/$turmaId'
    | '/turmas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/financeiro'
    | '/painel'
    | '/alunos/$alunoId'
    | '/demandas/casamento'
    | '/demandas/ensaio'
    | '/demandas/festa-aniversario'
    | '/turmas/$turmaId'
    | '/turmas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/painel'
    | '/_authenticated/alunos/$alunoId'
    | '/_authenticated/demandas/casamento'
    | '/_authenticated/demandas/ensaio'
    | '/_authenticated/demandas/festa-aniversario'
    | '/_authenticated/turmas/$turmaId'
    | '/_authenticated/turmas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alunos/$alunoId': {
      id: '/_authenticated/alunos/$alunoId'
      path: '/alunos/$alunoId'
      fullPath: '/alunos/$alunoId'
      preLoaderRoute: typeof AuthenticatedAlunosAlunoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandas/casamento': {
      id: '/_authenticated/demandas/casamento'
      path: '/demandas/casamento'
      fullPath: '/demandas/casamento'
      preLoaderRoute: typeof AuthenticatedDemandasCasamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandas/ensaio': {
      id: '/_authenticated/demandas/ensaio'
      path: '/demandas/ensaio'
      fullPath: '/demandas/ensaio'
      preLoaderRoute: typeof AuthenticatedDemandasEnsaioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandas/festa-aniversario': {
      id: '/_authenticated/demandas/festa-aniversario'
      path: '/demandas/festa-aniversario'
      fullPath: '/demandas/festa-aniversario'
      preLoaderRoute: typeof AuthenticatedDemandasFestaAniversarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/turmas/': {
      id: '/_authenticated/turmas/'
      path: '/turmas'
      fullPath: '/turmas/'
      preLoaderRoute: typeof AuthenticatedTurmasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/turmas/$turmaId': {
      id: '/_authenticated/turmas/$turmaId'
      path: '/turmas/$turmaId'
      fullPath: '/turmas/$turmaId'
      preLoaderRoute: typeof AuthenticatedTurmasTurmaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedAlunosAlunoIdRoute: typeof AuthenticatedAlunosAlunoIdRoute
  AuthenticatedDemandasCasamentoRoute: typeof AuthenticatedDemandasCasamentoRoute
  AuthenticatedDemandasEnsaioRoute: typeof AuthenticatedDemandasEnsaioRoute
  AuthenticatedDemandasFestaAniversarioRoute: typeof AuthenticatedDemandasFestaAniversarioRoute
  AuthenticatedTurmasTurmaIdRoute: typeof AuthenticatedTurmasTurmaIdRoute
  AuthenticatedTurmasIndexRoute: typeof AuthenticatedTurmasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedAlunosAlunoIdRoute: AuthenticatedAlunosAlunoIdRoute,
  AuthenticatedDemandasCasamentoRoute: AuthenticatedDemandasCasamentoRoute,
  AuthenticatedDemandasEnsaioRoute: AuthenticatedDemandasEnsaioRoute,
  AuthenticatedDemandasFestaAniversarioRoute:
    AuthenticatedDemandasFestaAniversarioRoute,
  AuthenticatedTurmasTurmaIdRoute: AuthenticatedTurmasTurmaIdRoute,
  AuthenticatedTurmasIndexRoute: AuthenticatedTurmasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
